sudo: false

language: node_js
node_js:
  - 8

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm test

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: gh-pages
  local_dir: build
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
